### PR TITLE
feat(charts): sablier helm chart for kube deployement

### PR DESCRIPTION
**Pull request by DrummyFloyd**
Hi , like i said i n the issue, seems to be a good idea to have a chart to easily deploy sablier

* templates
* unittest
* ci-lint test (ct lint/install  and helm unittest)
* readme generation docs with helm-docs
* ct-releaser => may not fully functionnal

NB: not very used to work with gh-actions, double check ^^

Closed: #271

### CODE REVIEW

**Comment by acouvreur** [comment]
Hey @DrummyFloyd ! Thanks a lot for your contribution, I will look into it :)

**Comment by acouvreur** [comment]
I'm not familiar with what's being done in most projects, should we have a folder `charts` ? A folder `helm` ? Should we place the folder `charts` inside the folder `helm` ?

Also for all the CI part I'm not familiar with helm testing.

I'll need some time reviewing this 👍 

This is some serious work though, thanks a lot for your contributions!

**Comment by DrummyFloyd** [comment]
> I'm not familiar with what's being done in most projects, should we have a folder `charts` ? A folder `helm` ? Should we place the folder `charts` inside the folder `helm` ?
>  no it's quite a convention the `charts` folders then inside u will find all yours chart look for instance the [grafana-repo](https://github.com/grafana/helm-charts)
> Also for all the CI part I'm not familiar with helm testing.
>  for the CI part, is quite simple i use what i used on my own stuff + was inspired byt other open source stuff like [traefik-chart](https://github.com/traefik/traefik-helm-chart/tree/master/traefik/tests)
if you need some explanation do not hesitate =) 
but for me the most important part is the unittest stuff, the `ct install` can be optionnal but could improve the test on the charts 
> I'll need some time reviewing this 👍
> 
> This is some serious work though, thanks a lot for your contributions!
:+1:

**Comment by acouvreur** [comment]
Hello @DrummyFloyd 

I will create a new PR heavily inspired from your work.

I'll mark you as a co author on the commit and this PR will be referenced!

I'll close this PR once I'll submit the new one.

**Comment by DrummyFloyd** [comment]
> Hello @DrummyFloyd
> 
> I will create a new PR heavily inspired from your work.
> 
> I'll mark you as a co author on the commit and this PR will be referenced!
> 
> I'll close this PR once I'll submit the new one.

Np problem =)

**Comment by acouvreur** [comment]
The main issue is that the current CI you are using sets up a chart repository using the github pages.

Currently the github pages feature is used to host the documentation.

I'll check what I can do.

**Comment by acouvreur** [comment]
We should also take car of helm best practices: https://helm.sh/docs/chart_best_practices/

There are some changes to be done for sa and rbac

**Comment by acouvreur** [comment]
With the way I will be deploying multi versioned documentation, this will enable me to publish the helm chart!

**Comment by basti-nis** [comment]
Any updates on this @acouvreur 
We want to deploy sablier in a large EKS cluster for our customer, but we're waiting until the helm chart is merged. Thanks a lot and I appreciate your work!

**Comment by acouvreur** [comment]
I'm quite busy at the moment, but I think I can finish working on this next week :)

**Comment by acouvreur** [comment]
Hello everyone, as mentioned I will be moving this to a new organization. So I've actually baked the helm chart: https://github.com/sablierapp/helm-charts

You can start testing it! I'm sure there will be some issues but it's a first :)

**Pull request closed without merging**
