### PR TITLE
Feature/project rewrite

### PR DESCRIPTION
**Pull request by acouvreur**
Full rewrite which will be version 2.0 which will provide more friendly go apis

### CODE REVIEW

**Comment by ab623** [comment]
How is the rewrite going? Keen to see the improved version!

**Comment by acouvreur** [comment]
Almost everything is finished
I started working on the UI but I'm working at a very slow pace right now.
I have my main focus on different things.

I will probably release the rewrite to beta first and add the UI afterwards.

Overall system is more stable and resilient.

It's more like a developer experience rewrite also, as Sablier is one of my first big project in Go, I've developed the project with Java enterprise habits which I'm trying to fix in the rewrite branch.

Feel free to dive in.

I'll update this draft to add a to-do list up to date with the project :)

**Comment by justmiles** [comment]
Hey @acouvreur, this is looking great. I've added a provider for Nomad and am cleaning a few things up before submitting a PR. Should I wait for this refactor?

**Comment by acouvreur** [comment]
> Hey @acouvreur, this is looking great. I've added a provider for Nomad and am cleaning a few things up before submitting a PR. Should I wait for this refactor?

Hello @justmiles, thanks for your contribution! It looks really promising!

I think you can target the beta branch, and I will do the migration myself to new project rewrite

**Comment by ab623** [comment]
Should this be closed? Surely it should stay open until the rewrite is complete.

**Comment by acouvreur** [comment]
Yes you're right, the bot was a bit aggressive on issues and PRs.

**Comment by acouvreur** [comment]
Actually, this is a common developper mistake, instead of changing the project piece by piece I wanted to move it all at once and now it's overwhelming!

I've started integrating a lot of the feature in this branch as small PRs.

I will keep doing that and close this PR :)

**Pull request closed without merging**
